name: Check Code Style
on:
  - push
  - pull_request

jobs:
  run-black:
    name: Black
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Run Black
        run: poetry run black --check pycave

  run-isort:
    name: Isort
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Run isort
        run: poetry run isort --check pycave

  run-pylint:
    name: Pylint
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Run Pylint
        run: poetry run pylint pycave

  run-pyright:
    name: Pyright
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_16.x | bash \
          && apt-get install -y nodejs
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | \
          python - \
          && echo "PATH=$HOME/.poetry/bin:$PATH" >> $GITHUB_ENV
      - name: Install Dependencies
        run: poetry install --no-root --no-interaction --no-ansi
      - name: Install Npm Dependencies
        run: npm ci
      - name: Run PyRight
        run: poetry run npm run lint
